export const MAIN_COLORS = ["#52ebcf", "#ff9292", "#ffff47"];

export const SUPPORTING_COLORS = [
  "#ff9292",
  "#ff9900",
  "#ffff47",
  "#6cff6c",
  "#52ebcf",
  "#9fc5e8",
  "#e892ff",
];

export const SLOGAN = "Shift how you gift with Wrapped";

export const GENDER_OPTIONS = ["Male", "Female", "Prefer not to say"] as const;

export const SPORTS_OPTIONS = [
  "American Soccer (Football)",
  "Cricket",
  "Basketball",
  "Tennis",
  "Volleyball",
  "Table Tennis",
  "Baseball",
  "Golf",
  "American Football",
  "Rugby",
  "Badminton",
  "Ice Hockey",
  "Field Hockey",
  "Boxing",
  "Mixed Martial Arts (MMA)",
  "Formula 1 Racing",
  "Swimming",
  "Athletics (Track & Field)",
  "Cycling",
  "Gymnastics",
  "Wrestling",
  "Skiing (Alpine)",
  "Cross-Country Skiing",
  "Snowboarding",
  "Figure Skating",
  "Speed Skating",
  "Surfing",
  "Skateboarding",
  "Lacrosse",
  "Softball",
  "Handball",
  "Water Polo",
  "Polo",
  "Squash",
  "Racquetball",
  "Fencing",
  "Archery",
  "Rowing",
  "Canoeing",
  "Kayaking",
  "Sailing",
  "Triathlon",
  "Weightlifting",
  "Powerlifting",
  "Judo",
  "Karate",
  "Taekwondo",
  "Brazilian Jiu-Jitsu",
  "Muay Thai",
  "Kickboxing",
  "Billiards (Pool)",
  "Snooker",
  "Darts",
  "Bowling",
  "Equestrian (Show Jumping)",
  "Dressage",
  "Eventing",
  "Sport Climbing",
  "Ultimate Frisbee",
  "Disc Golf",
  "Pickleball",
  "Chess",
  "Cornhole",
  "Cheerleading",
  "DanceSport",
  "Curling",
  "Bobsleigh",
  "Skeleton",
  "Luge",
  "Biathlon",
  "Nordic Combined",
  "Freestyle Skiing",
  "Diving",
  "Synchronized Swimming (Artistic Swimming)",
  "Open Water Swimming",
  "Fishing (Sport Fishing)",
  "Dragon Boat Racing",
  "Jet Ski Racing",
  "Auto Racing (NASCAR)",
  "Rally Racing",
  "MotoGP (Motorcycle Racing)",
  "Motocross",
  "Speedway Motorcycle Racing",
  "Netball",
  "Sepak Takraw",
  "Kabaddi",
  "Gaelic Football",
  "Hurling",
  "Australian Rules Football",
  "Extreme ironing",
];

export const SCENT_OPTIONS = [
  { name: "Vanilla", description: "warm, sweet, creamy" },
  { name: "Jasmine", description: "rich, white floral" },
  { name: "Rose", description: "classic, fresh floral" },
  { name: "Lavender", description: "clean, herbal floral" },
  { name: "Sandalwood", description: "smooth, woody, creamy" },
  { name: "Musk", description: "soft, skin-like, sensual" },
  { name: "Amber", description: "warm, resinous, slightly sweet" },
  { name: "Bergamot", description: "bright, citrusy, slightly spicy" },
  { name: "Cedarwood", description: "dry, woody, earthy" },
  { name: "Patchouli", description: "earthy, rich, slightly sweet" },
  { name: "Peony", description: "light, fresh floral" },
  { name: "Coconut", description: "creamy, tropical, sweet" },
  { name: "Lemon", description: "crisp, zesty citrus" },
  { name: "Orange Blossom", description: "sweet, fresh white floral" },
  { name: "Black Currant", description: "fruity, tart, juicy" },
];

export const MAX_SCENTS = 10;
